bobo/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import PromotionViewSet, MainView, PromotionDetailView, DiaperListView,CategoryListView
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('promotions', PromotionViewSet, basename='promotions')

urlpatterns = [
    path('api/', include(router.urls)),
    path('', MainView.as_view(), name='home'),
    path('okazje/<int:pk>/', PromotionDetailView.as_view(), name='okazja'),
    path('pieluchy/', DiaperListView.as_view(), name='pieluchy'),
    path('kategoria/', CategoryListView.as_view(), name='kategoria')
    #path('viewset/<int:pk>/', include(router.urls)),
]

bobowe/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bobo.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bobo/models.py
from django.db import models
from django.utils import timezone


class Promotion(models.Model):

    CATEGORY = [
        ('INN', 'inne'),
        ('ZAB', 'zabawki'),
        ('NEW', 'dla niemowlaka'),
        ('NAU', 'nauka'),
        ('PIE', 'pielęgnacja'),
        ('WIF', 'wózki i foteliki')
    ]

    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    price = models.FloatField(blank=True, null=True)
    old_price = models.FloatField(blank=True, null=True)
    # todo userselect > autoselect from link > default shop > default
    # todo img saving path would be unique for each entry
    # todo create image also different file as thumbnail
    image = models.ImageField(default='default.jpg', upload_to='promo_img', max_length=254, blank=True)
    shop = models.CharField(max_length=100) #todo linked to shop model or be "select or add" field
    category = models.CharField(max_length=100, choices=CATEGORY, default='INN')
    active = models.BooleanField()
    highlight = models.BooleanField(default=False)
    online = models.BooleanField()
    weblink = models.URLField(max_length=200, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    startdate = models.DateTimeField(default=timezone.now)
    enddate = models.DateTimeField(blank=True, null=True) #todo if we reach end date active should change to false
    #todo if enddate is close to now there should be somekind of notification

    @property
    def discount(self):
        discount = round(((self.old_price - self.price) / self.old_price * 100), 2)
        return discount

    def __str__(self):
        return self.title

#TODO auto generate and add affilate part of link for ex. allegro.pl
#TODO use bitly api, for automatic shorten link, and get click report for link



class Diaper(models.Model):
    name = models.CharField(max_length=100)
    brand = models.CharField(max_length=100)
    size = models.CharField(max_length=100, blank=True)
    online = models.BooleanField()
    weblink = models.URLField(blank=True)
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()

    @property
    def price_pp(self):  #price per piece
        ppp = int(self.price / self.quantity * 100)
        return ppp


    def __str__(self):
        if self.size:
            return self.brand + ' ' + self.name + ' ' + self.size
        else:
            return self.brand + ' ' + self.name

    #image



# Create your models here.

#TODO
#shop model - [name, type, link, image ]

bobo/views.py
from django.shortcuts import render
from django.db.models import Q
from rest_framework import viewsets
from .models import Promotion, Diaper
from .serializers import PromotionSerializer
from django.views.generic import ListView, DetailView, CreateView, UpdateView
import random
import string

class MainView(ListView):
    model = Promotion
    template_name = 'bobo/home.html'
    context_object_name = 'promotions'
    paginate_by = 5 #Will be expand to 10
    ordering = ['-date']

    #Search field from navbar modify queryset
    def get_queryset(self):
        if self.request.GET.get('search'):
            search_field = self.request.GET.get('search') if self.request.GET.get('search') else '123'
            return Promotion.objects.filter(Q(title__icontains=search_field) |
                                            Q(shop__icontains=search_field)
            ).order_by('-date')
        else:
            return Promotion.objects.all().order_by('-date')


class PromotionDetailView(DetailView):
    model = Promotion


class DiaperListView(ListView):
    model = Diaper
    template_name = 'bobo/diapers.html'
    context_object_name = 'diapers'

class CategoryListView(ListView):
    model = Promotion
    template_name = 'bobo/category.html'
    context_object_name = 'promotions'
    #TODO paginate not working with geting url parameter
    paginate_by = 5 #Will be expand to 10

    category_list = model.CATEGORY

    def get_queryset(self):
        return Promotion.objects.filter(category=self.request.GET.get('category')).order_by('-date')


#API viewset
class PromotionViewSet(viewsets.ModelViewSet):
    serializer_class = PromotionSerializer
    queryset = Promotion.objects.all().order_by('-date')


# Create Promotion obj for testing

def promotion_add(number):

    category = ['INN', 'ZAB', 'NEW', 'NAU', 'PIE', 'WIF']
    shop_list = ['biedronka', 'sizeer', 'allegro', 'al.to', 'osiedlowy', 'mięsny', 'dino']


    for x in range(number):

        obj = Promotion.objects.create(
            title='Promocja Testowa {}'.format(x),
            description=''.join(random.choices(string.ascii_uppercase + string.digits, k=100)),
            shop=random.choice(shop_list),
            category=random.choice(category),
            active=random.choice(['True', 'False']),
            online=random.choice(['True', 'False'])
        )
        obj.save()

bobo/templates/bobo/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="shortcut icon" type="image/png" href="{% static 'bobo/favicon.ico' %}"/>
    <title>Najlepsze Okazje dla Rodziców</title>
  </head>

  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'bobo/logo_nav.jpg' %}" alt="" width="30" height="24">
            BOBOWE.PL
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Testowy</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pieluchy' %}">Pampersy</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Kategorie
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'kategoria' %}">Kategorie</a></li>
                <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'kategoria' %}?category=NEW">Dla Niemowlaków</a></li>
                <li><a class="dropdown-item" href="{% url 'kategoria' %}?category=ZAB">Zabawki</a></li>
                <li><a class="dropdown-item" href="{% url 'kategoria' %}?category=PIE">Pielęgnacyjna</a></li>
                  <li><a class="dropdown-item" href="{% url 'kategoria' %}?category=NAU">Edukacja</a></li>
                  <li><a class="dropdown-item" href="{% url 'kategoria' %}?category=WIF">Wózki i foteliki</a></li>
                  <li><a class="dropdown-item" href="{% url 'kategoria' %}?category=INN">Inne</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="d-flex" action="{% url 'home' %}">
            <input class="form-control me-2" type="search" name="search" placeholder="Znajdź okazję"
                   value="{{  request.get.GET }}" aria-label="Search">
            <button class="btn btn-outline-warning" type="submit">Szukaj</button>
          </form>
        </div>
      </div>
    </nav>
    <div class="container">

    {% block content %} {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </div>
    </header>
  </body>
</html>

bobo/templates/bobo/category.html
{% extends 'bobo/base.html' %}
{% load static %}
{% block content %}

{% with promotions|first as first_promotion %}
<h1 class="mt-4">{{ first_promotion.get_category_display|capfirst }}</h1>
{% endwith %}
<hr>

{% if request.GET.category %}

{% for promo in promotions %}

<div class="card mb-3" style="max-width: 720px;">
  <div class="row g-0">
    <div class="col-md-4">
        <a href="{% url 'okazja' promo.id %}">
      <img src="{{ MEDIA_URL }}{{promo.image}}" class="img-fluid rounded-start" alt="...">
        </a>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">
            <a href="{% url 'okazja' promo.id %}" class="link-dark">{{ promo.title }}</a> </h5>
        <p class="card-text">{{  promo.description }} - This is a wider card with supporting text below as a natural
            lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div>


{% endfor %}

{% if is_paginated %}

    {% if page_obj.has_previous %}
        <a class="btn btn-outline-warning mb-4" href="?page=1">Pierwsza</a>
        <a class="btn btn-outline-warning mb-4" href="?page={{ page_obj.previous_page_number }}">Poprzednia</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-dark mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-dark mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

       {% if page_obj.has_next %}
        <a class="btn btn-outline-warning mb-4" href="?page={{ page_obj.next_page_number }}">Następna</a>
        <a class="btn btn-outline-warning mb-4" href="?page={{ page_obj.paginator.num_pages }}">Ostatnia</a>
    {% endif %}
{% endif %}

{%  else %}
    <div class="d-grid gap-2">
    {% for category in view.category_list %}

        <a href="{% url 'kategoria' %}?category={{ category.0 }}" class="btn btn-warning btn-lg">
            {{ category.1|capfirst }}</a>

    {% endfor %}
    </div>
{% endif %}

{% endblock %}

bobo/templates/bobo/diapers.html
{% extends 'bobo/base.html' %}
{% load static %}
{% block content %}

<h1 class="mt-4">Najlepsze okazje na pieluchy</h1>

<table class="table table-hover">
  <thead class="table-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Marka</th>
      <th scope="col">Nazwa</th>
      <th scope="col">Rozmiar</th>
      <th scope="col">Cena</th>
      <th scope="col">Ilość w paczce</th>
      <th scope="col">Cena za 1 szt</th>
      <th scope="col">Dostępna Online</th>
      <th scope="col">KUP</th>

    </tr>
  </thead>
  <tbody>
  {% for diaper in diapers %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ diaper.brand }}</td>
      <td>{{ diaper.name }}</td>
      <td>{{ diaper.size }}</td>
      <td>{{ diaper.price }} zł</td>
      <td>{{ diaper.quantity }}</td>
      <td>{{ diaper.price_pp }} gr</td>
      <td>{% if diaper.online %} TAK {% else %} - {% endif %}</td>
      <td>{% if diaper.weblink %}
          <a class="btn btn-warning" href="{{ diaper.weblink }}" role="button">KUP</a>
          {% else %} - {% endif %}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

bobo/templates/bobo/home.html
{% extends 'bobo/base.html' %}
{% load static %}
{% block content %}




{% if request.GET.search %}
    <h2 class="mt-4">Wynik Wyszukiwania: "{{ request.GET.search}}"</h2>
{% else %}
    <h1 class="mt-4">Najlepsze Okazje dla Rodziców</h1>
{% endif %}

<hr>
{% for promo in promotions %}

<div class="card mb-3" style="max-width: 720px;">
  <div class="row g-0">
    <div class="col-md-4">
        <a href="{% url 'okazja' promo.id %}">
      <img src="{{ MEDIA_URL }}{{promo.image}}" class="img-fluid rounded-start" alt="...">
        </a>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">
            <a href="{% url 'okazja' promo.id %}" class="link-dark">{{ promo.title }}</a> </h5>
        <p>
            {% if promo.price and promo.old_price %}
                <span class="text-warning h4"><strong>{{ promo.price }}zł</strong></span>
            {% endif %}
            {% if promo.price and promo.old_price %}
                <s>{{ promo.old_price }}zł</s>
            {% endif %}
            {% if promo.price and promo.old_price %}
                <mark>-{{ promo.discount }}%</mark>
            {% endif %}</p>
        <p class="card-text">- This is a wider card with supporting
            text below as a natural
            lead-in to additional content. This content is a little bit longer.
            {{  promo.description|truncatechars:"200" }}
            {% if promo.description|length > 200 %}
                <a href="{% url 'okazja' promo.id %}" class="link-dark"><b>Czytaj dalej</b></a>
            {% endif %}
        </p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div>


{% endfor %}

{% if is_paginated %}

    {% if page_obj.has_previous %}
        <a class="btn btn-outline-warning mb-4" href="?page=1">Pierwsza</a>
        <a class="btn btn-outline-warning mb-4" href="?page={{ page_obj.previous_page_number }}">Poprzednia</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-dark mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-dark mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

       {% if page_obj.has_next %}
        <a class="btn btn-outline-warning mb-4" href="?page={{ page_obj.next_page_number }}">Następna</a>
        <a class="btn btn-outline-warning mb-4" href="?page={{ page_obj.paginator.num_pages }}">Ostatnia</a>
    {% endif %}
{% endif %}

{% endblock %}

bobo/templates/bobo/promotion_detail.html
{% extends 'bobo/base.html' %}
{% load static %}
{% block content %}

<h1 class="mt-3">{{  object.title }}</h1>

<div class="card mb-3" style="max-width: 720px;">
  <div class="row g-0">
    <div class="col-md-4">
        <a href="{{ object.image.url }}">
      <img src="{{ MEDIA_URL }}{{object.image}}" class="img-fluid rounded-start" alt="...">
        </a>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ object.title }}
            <a class="btn btn-warning" href="{{ object.weblink }}" role="button">Idź do okazji</a>
        </h5>
        <hr>
            <a href="#" class="link-dark h6">{{ object.shop }}</a>
        <hr>
            <a href="#" class="btn btn-dark btn-sm">{{ object.get_category_display|capfirst }}</a>
        <hr>
          <p class="h6">Start: {{ object.startdate|date:"l d.m.y - G:i"}}</p>
          {% if object.enddate %}
          <p class="h6">Koniec: {{ object.enddate|date:"l d.m.y - G:i" }}</p>
          {% endif %}
          <hr>

        <p class="card-text">{{  object.description }} - This is a wider card with supporting text below as a natural
            lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div>

{% endblock %}

<!--
    active = models.BooleanField()
    online = models.BooleanField()
    weblink = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    startdate = models.DateTimeField(default=timezone.now)
    enddate = models.DateTimeField(blank=True, null=True) #todo if we reach end date active should change to false